apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
labels:
- includeSelectors: true
  pairs:
    env: prod
patches:
- path: deployment-patch.yaml
- path: service-patch.yaml
namePrefix:
  prod-
configMapGenerator:
  - name: nginx-html
    files:
      - index.html
