apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
labels:
- includeSelectors: true
  pairs:
    env: dev
patches:
- path: deployment-patch.yaml
- path: service-patch.yaml
- path: html-patch.yaml
# namePrefix:
#   dev-
# replacements:
# - source:
#     kind: ConfigMap
#     name: nginx-html
#   targets:
#   - select:
#       kind: Deployment
#       name: nginx
#     fieldPaths:
#     - spec.template.spec.containers
configMapGenerator:
  - name: nginx-html
    files:
      - index.html
